"""New Migration

Revision ID: 9d9adaa18f9c
Revises:
Create Date: 2021-07-07 11:37:04.639123

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '9d9adaa18f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('time_created', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('time_updated', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
